name: Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: docker-compose build dev
    - name: run lint
      run: docker-compose run --rm dev make lint
    - name: run tests
      run: docker-compose run --rm dev make test
